# Generated by Django 2.2.5 on 2019-09-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190914_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='C:\\Users\\Miner\\Desktop\\portfolio\\projects\\static\\img'),
        ),
    ]
