# Generated by Django 2.2.5 on 2019-09-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(default='https://www.hdwallpapers.in/walls/windows_xp_bliss-wide.jpg', max_length=1000),
        ),
    ]
