# Generated by Django 2.2.8 on 2020-09-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190919_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=250, null=True, unique=True),
        ),
    ]
